# Generated by Django 5.2.2 on 2026-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_profile_latitude_alter_profile_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified_seller",
        ),
        migrations.RemoveField(
            model_name="user",
            name="points",
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("superadmin", "Super Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("superadmin", "Super Admin"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
