# Generated by Django 5.2.2 on 2026-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_user_is_verified_seller_remove_user_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
    ]
