# Generated by Django 5.2.2 on 2026-02-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_emailverification_role_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address_line",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="region",
        ),
    ]
