# Generated by Django 5.2.2 on 2026-03-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_profile_address_line_profile_city_profile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=50, max_digits=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=50, max_digits=50, null=True
            ),
        ),
    ]
