# Generated by Django 5.2.2 on 2026-03-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_profile_latitude_alter_profile_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
    ]
