# Generated by Django 5.2.2 on 2026-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_notification_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("product_approved", "Product Approved"),
                    ("product_rejected", "Product Rejected"),
                    ("order_created", "Order Created"),
                    ("order_shipped", "Order Shipped"),
                    ("system_alert", "System Alert"),
                    ("wishlist_discount", "Wishlist Discount"),
                    ("order_created", "Order Created"),
                    ("order_processing", "Order Processing"),
                    ("order_shipped", "Order Shipped"),
                    ("order_delivered", "Order Delivered"),
                    ("order_completed", "Order Completed"),
                    ("order_cancelled", "Order Cancelled"),
                    ("order_refunded", "Order Refunded"),
                    ("refund_requested", "Refund Requested"),
                    ("refund_approved", "Refund Approved"),
                    ("refund_rejected", "Refund Rejected"),
                    ("low_stock", "Low Stock"),
                    ("return_status_update", "Return Status Update"),
                    ("return_status_update_buyer", "Return Status Update (Buyer)"),
                    ("brand_approved", "Brand Approved"),
                    ("brand_rejected", "Brand Rejected"),
                    ("brand_request_submitted", "Brand Request Submitted"),
                    ("auction_new_bid", "Auction New Bid"),
                    ("auction_outbid", "Auction Outbid"),
                    ("auction_won", "Auction Won"),
                    ("auction_ended_no_winner", "Auction Ended No Winner"),
                    ("auction_order_created", "Auction Order Created"),
                    ("auction_submitted", "Auction Submitted"),
                    ("auction_approved", "Auction Approved"),
                    ("auction_rejected", "Auction Rejected"),
                    ("auction_cancelled", "Auction Cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
