# Generated by Django 5.2.2 on 2026-03-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_emaildeliverylog"),
        ("orders", "0008_remove_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Order Created"),
                    ("order_shipped", "Order Shipped"),
                    ("system_alert", "System Alert"),
                    ("wishlist_discount", "Wishlist Discount"),
                    ("order_processing", "Order Processing"),
                    ("order_delivered", "Order Delivered"),
                    ("order_completed", "Order Completed"),
                    ("order_cancelled", "Order Cancelled"),
                    ("order_refunded", "Order Refunded"),
                    ("refund_requested", "Refund Requested"),
                    ("refund_approved", "Refund Approved"),
                    ("refund_rejected", "Refund Rejected"),
                    ("low_stock", "Low Stock"),
                    ("return_status_update", "Return Status Update"),
                    ("return_status_update_buyer", "Return Status Update (Buyer)"),
                    ("auction_new_bid", "Auction New Bid"),
                    ("auction_outbid", "Auction Outbid"),
                    ("auction_won", "Auction Won"),
                    ("auction_ended_no_winner", "Auction Ended No Winner"),
                    ("auction_order_created", "Auction Order Created"),
                    ("auction_cancelled", "Auction Cancelled"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_log",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EmailDeliveryLog",
        ),
    ]
