# Generated by Django 5.2.2 on 2026-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0012_alter_notification_notification_type_emaillog_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Order Created"),
                    ("order_shipped", "Order Shipped"),
                    ("system_alert", "System Alert"),
                    ("wishlist_discount", "Wishlist Discount"),
                    ("order_processing", "Order Processing"),
                    ("order_delivered", "Order Delivered"),
                    ("order_completed", "Order Completed"),
                    ("order_cancelled", "Order Cancelled"),
                    ("order_refunded", "Order Refunded"),
                    ("refund_requested", "Refund Requested"),
                    ("refund_approved", "Refund Approved"),
                    ("refund_rejected", "Refund Rejected"),
                    ("low_stock", "Low Stock"),
                    ("auction_new_bid", "Auction New Bid"),
                    ("auction_outbid", "Auction Outbid"),
                    ("auction_won", "Auction Won"),
                    ("auction_ended_no_winner", "Auction Ended No Winner"),
                    ("auction_order_created", "Auction Order Created"),
                    ("auction_cancelled", "Auction Cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
