# Generated by Django 5.2.2 on 2026-02-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_assigned_at_order_assigned_delivery_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="assigned_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="assigned_delivery",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_fee",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="seller",
        ),
    ]
