# Generated by Django 5.2.2 on 2026-02-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_order_assigned_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivered_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address_line",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_latitude",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_longitude",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_postal_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_region",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Refund",
        ),
    ]
