# Generated by Django 5.2.2 on 2026-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
