# Generated by Django 5.2.2 on 2026-02-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_category_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="producteditrequest",
            name="seller",
        ),
        migrations.DeleteModel(
            name="SellerBlock",
        ),
    ]
