# Generated by Django 5.2.2 on 2026-03-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_remove_product_seller_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editrequestimage",
            name="edit_request",
        ),
        migrations.RemoveField(
            model_name="producteditrequest",
            name="product",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="description",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="rejection_reason",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="product",
            name="disapproval_reason_ar",
        ),
        migrations.RemoveField(
            model_name="product",
            name="disapproval_reason_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
        migrations.DeleteModel(
            name="BrandBlock",
        ),
        migrations.DeleteModel(
            name="EditRequestImage",
        ),
        migrations.DeleteModel(
            name="ProductEditRequest",
        ),
    ]
