# Generated by Django 5.2.2 on 2026-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_auction_seller_auction_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="rejection_reason",
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("ended", "Ended"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
